# Generated by Django 5.1.15 on 2026-04-27 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_marketplace_core_v6_10_safe_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(max_length=32)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('rules_json', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=32)),
                ('progress_value', models.IntegerField(default=0)),
                ('target_value', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='challenges.challenge')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to='customers.customerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
