# Generated by Django 5.1.15 on 2026-07-10 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cohort', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='cohorts.groupprogram'),
        ),
        migrations.CreateModel(
            name='ProgressCheckpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('checkpoint_type', models.CharField(choices=[('content', 'Content'), ('attendance', 'Attendance'), ('task', 'Task'), ('measurement', 'Measurement')], max_length=32)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='cohorts.cohort')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortDashboardSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_checkpoint_progress', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshots', to='cohorts.cohort')),
            ],
            options={
                'unique_together': {('cohort', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentCheckpointProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_progress', to='cohorts.cohortenrollment')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_progress', to='cohorts.progresscheckpoint')),
            ],
            options={
                'unique_together': {('enrollment', 'checkpoint')},
            },
        ),
    ]
