services:
  postgres:
    ports:
      - "5434:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  worker:
    volumes:
      - ./backend:/app/backend

  beat:
    volumes:
      - ./backend:/app/backend

  flower:
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app/backend
