[mypy]
python_version = 3.13
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = False
exclude = (?x)(^frontend/|^deploy/|^ops/)

[mypy-config.*]
ignore_errors = True
