[mypy]
python_version = 3.12
explicit_package_bases = True
ignore_missing_imports = True
exclude = (?x)(
    ^\.venv/
    | ^.*?/migrations/
    | ^integration_snippets/
    | ^.*?/integration_snippets/
    | ^tests/
    | ^.*?/tests/
  )
disable_error_code =
    annotation-unchecked,
    arg-type,
    assignment,
    attr-defined,
    dict-item,
    import-untyped,
    index,
    misc,
    no-redef,
    operator,
    typeddict-item,
    truthy-function,
    union-attr,
    valid-type,
    var-annotated
