# Generated by Django 5.1.15 on 2026-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerkycprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
