# Generated by TrainerHub v8.28.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('degraded', 'Degraded'), ('critical', 'Critical')], default='ok', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('repair', 'Repair'), ('ci', 'CI')], default='manual', max_length=16)),
                ('generated_at', models.DateTimeField(default=timezone.now)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('section_statuses', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationsnapshot',
            index=models.Index(fields=['status', 'generated_at'], name='ops_rec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsnapshot',
            index=models.Index(fields=['source', 'generated_at'], name='ops_rec_source_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsnapshot',
            index=models.Index(fields=['generated_at'], name='ops_rec_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsnapshot',
            index=models.Index(fields=['critical_count', 'total_issues'], name='ops_rec_counts_idx'),
        ),
    ]
