# Generated by Django 5.1.15 on 2026-04-27 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitStreakState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habit_plan_id', models.UUIDField(unique=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('freeze_tokens', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habits_streak_state',
            },
        ),
        migrations.CreateModel(
            name='ProgressJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('habit_plan_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cohort_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('mood', models.CharField(blank=True, default='', max_length=32)),
                ('energy', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField()),
                ('visibility', models.CharField(default='private', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'habits_progress_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='UserHabitSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('active_habits', models.PositiveIntegerField(default=0)),
                ('completed_today', models.PositiveIntegerField(default=0)),
                ('missed_today', models.PositiveIntegerField(default=0)),
                ('aggregate_current_streak', models.PositiveIntegerField(default=0)),
                ('aggregate_longest_streak', models.PositiveIntegerField(default=0)),
                ('completion_rate_7d', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('completion_rate_30d', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habits_user_snapshot',
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habit_plan_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('checkin_date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'habits_daily_checkin',
                'indexes': [models.Index(fields=['user_id', 'checkin_date'], name='habits_dail_user_id_bf1e2c_idx')],
                'unique_together': {('habit_plan_id', 'checkin_date')},
            },
        ),
        migrations.CreateModel(
            name='HabitPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('cohort_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('category', models.CharField(default='general', max_length=64)),
                ('cadence', models.CharField(default='daily', max_length=32)),
                ('target_value', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='times', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habits_habit_plan',
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='habits_habi_user_id_d6da0d_idx'), models.Index(fields=['cohort_id'], name='habits_habi_cohort__48c9bd_idx')],
            },
        ),
    ]
