# Generated by Django 5.1.15 on 2026-07-10 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=32, unique=True)),
                ('dispute_type', models.CharField(choices=[('refund', 'Refund'), ('chargeback', 'Chargeback'), ('support', 'Support')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='new', max_length=20)),
                ('trainer_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargebackOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_case_id', models.CharField(blank=True, max_length=128)),
                ('network', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('status', models.CharField(default='open', max_length=32)),
                ('evidence_due_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('dispute_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chargeback_operation', to='disputes.disputecase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisputeEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispute_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='disputes.disputecase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('decision', models.CharField(default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('dispute_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_review', to='disputes.disputecase')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportInboxItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('channel', models.CharField(default='in_app', max_length=32)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_for_admin', models.BooleanField(default=True)),
                ('unread_for_user', models.BooleanField(default=False)),
                ('dispute_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_inbox_item', to='disputes.disputecase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['status', 'dispute_type'], name='disputes_di_status_d95e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['opened_at'], name='disputes_di_opened__ca3162_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['trainer_id'], name='disputes_di_trainer_c39164_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['order_id'], name='disputes_di_order_i_b539e6_idx'),
        ),
    ]
