# Generated by Django 5.1.15 on 2026-04-27 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('one_time', 'One-time'), ('subscription', 'Subscription')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('video', 'Video'), ('program', 'Program'), ('bundle', 'Bundle'), ('subscription_plan', 'Subscription plan')], max_length=32),
        ),
    ]
