# Generated by TrainerHub v8.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_item_id_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('awaiting_payment', 'Awaiting payment'),
                    ('paid', 'Paid'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                    ('failed', 'Failed'),
                    ('refunded', 'Refunded'),
                    ('disputed', 'Disputed'),
                    ('charged_back', 'Charged back'),
                ],
                default='pending',
                max_length=32,
            ),
        ),
    ]
