# Generated by Django 5.1.15 on 2026-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_documents', '0003_v112_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedocumentdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
