# Generated by TrainerHub v8.10

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_marketplace_core_v6_10_safe_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='external_event_id',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='provider',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='raw_payload_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='received_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='signature',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='received', max_length=24),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['provider', 'status'], name='payments_webhook_provider_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['event_type', 'received_at'], name='payments_webhook_type_received_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['payment', 'status'], name='payments_webhook_payment_status_idx'),
        ),
    ]
