# Generated by Django 5.1.15 on 2026-04-27 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcase',
            options={'ordering': ['priority', '-opened_at']},
        ),
        migrations.AlterModelOptions(
            name='moderationcaseevent',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='moderationreviewdecision',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='latest_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs changes'), ('escalated', 'Escalated')], max_length=32),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='target_type',
            field=models.CharField(choices=[('trainer_profile', 'Trainer profile'), ('content', 'Content'), ('program', 'Program'), ('document', 'Document')], max_length=64),
        ),
        migrations.AlterField(
            model_name='moderationreviewdecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs changes'), ('escalated', 'Escalated')], max_length=32),
        ),
        migrations.AlterField(
            model_name='trainerriskflag',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', 'queue'], name='moderation__status_f0e786_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['target_type', 'target_id'], name='moderation__target__2376b2_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerriskflag',
            index=models.Index(fields=['trainer', 'is_active'], name='moderation__trainer_9c437b_idx'),
        ),
    ]
