export const designTokens = {
  color: {
    background: 'var(--color-bg)',
    foreground: 'var(--color-foreground)',
    muted: 'var(--color-muted)',
    mutedForeground: 'var(--color-muted-foreground)',
    surface: 'var(--color-surface)',
    surfaceElevated: 'var(--color-surface-elevated)',
    surfaceGlass: 'var(--color-surface-glass)',
    surfaceMuted: 'var(--color-surface-muted)',
    surfaceStrong: 'var(--color-surface-strong)',
    dark: 'var(--color-dark)',
    text: 'var(--color-text)',
    textSoft: 'var(--color-text-soft)',
    textMuted: 'var(--color-text-muted)',
    textInverse: 'var(--color-text-inverse)',
    border: 'var(--color-border)',
    borderStrong: 'var(--color-border-strong)',
    primary: 'var(--color-primary)',
    primaryHover: 'var(--color-primary-hover)',
    primarySoft: 'var(--color-primary-soft)',
    accent: 'var(--color-accent)',
    accentSoft: 'var(--color-accent-soft)',
    success: 'var(--color-success)',
    successSoft: 'var(--color-success-soft)',
    warning: 'var(--color-warning)',
    warningSoft: 'var(--color-warning-soft)',
    danger: 'var(--color-danger)',
    dangerSoft: 'var(--color-danger-soft)',
  },
  radius: {
    xs: 'var(--radius-xs)',
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    pill: 'var(--radius-pill)',
  },
  spacing: {
    xs: 'var(--space-xs)',
    sm: 'var(--space-sm)',
    md: 'var(--space-md)',
    lg: 'var(--space-lg)',
    xl: 'var(--space-xl)',
    '2xl': 'var(--space-2xl)',
  },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    soft: 'var(--shadow-soft)',
    medium: 'var(--shadow-medium)',
    glow: 'var(--shadow-glow)',
  },
  layout: {
    containerMaxWidth: 'var(--container-max-width)',
  },
  typography: {
    fontFamily: 'var(--font-sans)',
    h1: 'var(--font-size-h1)',
    h2: 'var(--font-size-h2)',
    h3: 'var(--font-size-h3)',
    body: 'var(--font-size-body)',
    small: 'var(--font-size-small)',
  },
} as const;

export type DesignTokens = typeof designTokens;
