# Generated by Django 5.1.15 on 2026-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocampaign',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
