# Generated by Django 5.1.15 on 2026-07-10 15:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(choices=[('daily_checkin_completed', 'Daily check-in completed'), ('habit_streak_milestone', 'Habit streak milestone'), ('cohort_checkpoint_completed', 'Cohort checkpoint completed'), ('live_session_attended', 'Live session attended')], max_length=64)),
                ('points_delta', models.IntegerField(default=0)),
                ('badge_code', models.CharField(blank=True, max_length=64)),
                ('min_streak_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserRewardBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All time')], max_length=16)),
                ('snapshot_date', models.DateField()),
                ('rank', models.PositiveIntegerField()),
                ('points', models.IntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('badge_count', models.PositiveIntegerField(default=0)),
                ('cohort_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', '-snapshot_date', 'rank'],
                'indexes': [models.Index(fields=['period', 'snapshot_date', 'rank'], name='gamificatio_period_e9d01a_idx')],
                'unique_together': {('period', 'snapshot_date', 'rank'), ('period', 'snapshot_date', 'user', 'cohort_id')},
            },
        ),
        migrations.CreateModel(
            name='AchievementLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('source_event_id', models.CharField(blank=True, max_length=64)),
                ('points_delta', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('reward_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.rewardrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_f5eb75_idx'), models.Index(fields=['event_type'], name='gamificatio_event_t_8e8bfb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_event_type', models.CharField(blank=True, max_length=64)),
                ('source_event_id', models.CharField(blank=True, max_length=64)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badgedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
