#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR/backend"

# Remove known dangerous/accidental autogenerated migrations from interrupted global makemigrations runs.
# These names are safe to remove before they have been applied; if any were applied, Django will report it later.
rm -f apps/categories/migrations/0002_alter_category_id_alter_tag_id.py
rm -f apps/customers/migrations/0002_alter_customerprofile_id.py
rm -f apps/entitlements/migrations/0002_alter_entitlement_created_at_and_more.py
rm -f apps/favorites/migrations/0002_favorite_delete_favoritetrainer_and_more.py
rm -f apps/moderation/migrations/0002_alter_moderationcase_options_and_more.py
rm -f apps/orders/migrations/0002_alter_order_created_at_alter_order_order_type_and_more.py
rm -f apps/payments/migrations/0002_alter_payment_created_at_alter_payment_provider_and_more.py
rm -f apps/platform_settings/migrations/0002_alter_platformsettings_id.py
rm -f apps/products/migrations/0002_alter_product_id_alter_productitem_id.py
rm -f apps/purchases/migrations/0002_alter_purchase_id.py
rm -f apps/referrals/migrations/0001_initial.py
rm -f apps/subscriptions/migrations/0002_alter_subscription_created_at_and_more.py
rm -f apps/videos/migrations/0002_alter_mediaasset_id_alter_video_id.py
rm -f apps/challenges/migrations/0001_initial.py
rm -f apps/users/migrations/0002_alter_user_date_joined_alter_user_first_name_and_more.py
rm -f apps/habits/migrations/0001_initial.py
rm -f apps/audit/migrations/0001_initial.py

# The favorites migration is supplied manually because it must preserve legacy FavoriteTrainer data.
# Do not let Django autogenerate this one as a blind delete/create migration.

python manage.py check

# Generate only controlled per-app migrations. This avoids the unsafe global makemigrations flow.
python manage.py makemigrations \
  audit \
  challenges \
  referrals \
  habits \
  categories \
  customers \
  entitlements \
  moderation \
  orders \
  payments \
  platform_settings \
  products \
  purchases \
  subscriptions \
  videos \
  users \
  --name marketplace_core_v6_10_safe_schema

python manage.py makemigrations notifications --check --dry-run
python manage.py makemigrations payouts --check --dry-run
python manage.py makemigrations trainers --check --dry-run
python manage.py makemigrations favorites --check --dry-run

python manage.py migrate
python manage.py check
python manage.py makemigrations --check --dry-run
