# Generated by TrainerHub v8.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_webhook_ingestion_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created'),
                    ('pending', 'Pending'),
                    ('succeeded', 'Succeeded'),
                    ('failed', 'Failed'),
                    ('cancelled', 'Cancelled'),
                    ('refunded', 'Refunded'),
                    ('disputed', 'Disputed'),
                    ('charged_back', 'Charged back'),
                ],
                default='created',
                max_length=32,
            ),
        ),
    ]
