EXPORT_RUN_STATUS_DRAFT = "draft"
EXPORT_RUN_STATUS_QUEUED = "queued"
EXPORT_RUN_STATUS_EXPORTED = "exported"
EXPORT_RUN_STATUS_DELIVERED = "delivered"
EXPORT_RUN_STATUS_FAILED = "failed"
EXPORT_RUN_STATUS_SUPERSEDED = "superseded"

EXPORT_RUN_STATUSES = [
    (EXPORT_RUN_STATUS_DRAFT, "Draft"),
    (EXPORT_RUN_STATUS_QUEUED, "Queued"),
    (EXPORT_RUN_STATUS_EXPORTED, "Exported"),
    (EXPORT_RUN_STATUS_DELIVERED, "Delivered"),
    (EXPORT_RUN_STATUS_FAILED, "Failed"),
    (EXPORT_RUN_STATUS_SUPERSEDED, "Superseded"),
]

JOURNAL_BATCH_STATUS_DRAFT = "draft"
JOURNAL_BATCH_STATUS_FINALIZED = "finalized"
JOURNAL_BATCH_STATUS_EXPORTED = "exported"
JOURNAL_BATCH_STATUS_VOID = "void"

JOURNAL_BATCH_STATUSES = [
    (JOURNAL_BATCH_STATUS_DRAFT, "Draft"),
    (JOURNAL_BATCH_STATUS_FINALIZED, "Finalized"),
    (JOURNAL_BATCH_STATUS_EXPORTED, "Exported"),
    (JOURNAL_BATCH_STATUS_VOID, "Void"),
]

MAPPING_TARGET_LEDGER_ACCOUNT = "ledger_account"
MAPPING_TARGET_REVENUE_STREAM = "revenue_stream"
MAPPING_TARGET_TAX_CODE = "tax_code"
MAPPING_TARGET_PAYOUT_CLEARING = "payout_clearing"

MAPPING_TARGETS = [
    (MAPPING_TARGET_LEDGER_ACCOUNT, "Ledger account"),
    (MAPPING_TARGET_REVENUE_STREAM, "Revenue stream"),
    (MAPPING_TARGET_TAX_CODE, "Tax code"),
    (MAPPING_TARGET_PAYOUT_CLEARING, "Payout clearing"),
]

DOCUMENT_FORMAT_JSON = "json"
DOCUMENT_FORMAT_CSV = "csv"

DOCUMENT_FORMATS = [
    (DOCUMENT_FORMAT_JSON, "JSON"),
    (DOCUMENT_FORMAT_CSV, "CSV"),
]
