# Generated by Django 5.1.15 on 2026-04-27 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='source_type',
            field=models.CharField(choices=[('order', 'Order'), ('subscription', 'Subscription'), ('admin', 'Admin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='target_type',
            field=models.CharField(choices=[('video', 'Video'), ('program', 'Program'), ('bundle', 'Bundle'), ('library', 'Library')], max_length=32),
        ),
    ]
